version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.3
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

  api:
    image: gutenbooks/api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    depends_on:
      - db
    links:
      - db

volumes:
  db:
