version: '3.7'
services:
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

  api:
    image: gutenbooks/api
    build: ./api
    ports:
      - 8000:3000
    command: npm run start:dev
    volumes:
      - ./api/src:/app/src
      - ./api/ormconfig.js:/app/ormconfig.js
      - ./api/package.json:/app/package.json
      - ./api/test:/app/test
    env_file:
      - .env
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    depends_on:
      - db
    links:
      - db

  app:
    image: gutenbooks/app
    build: ./app
    command: npm start
    environment:
      - REACT_APP_API_DOMAIN=http://localhost:8000/
      - REACT_APP_GA_TRACKING_ID=UA-161511207-1
    volumes:
      - ./app/bin:/app/bin
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/package.json:/app/package.json
      - ./app/tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000

volumes:
  db:
